spring.application.name=StockTrading
spring.data.mongodb.uri=mongodb+srv://sumanyurajput2005_db_user:875A2Rv4WigJSQw1@cluster0.6oaz9wg.mongodb.net/stock_trading?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=stock_trading
server.port=8080
